# Generated by Django 2.2.5 on 2019-11-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='products')),
                ('category', models.CharField(choices=[('S', 'SCIENCE'), ('T', 'TECHNOLOGY'), ('E', 'ENGINEERING'), ('M', 'MATHEMATICS')], max_length=1)),
                ('language', models.CharField(choices=[('EN', 'ENGLISH'), ('AM', 'AMHARIC')], max_length=2)),
                ('status', models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('MW', 'MOST WATCHED'), ('TR', 'TOP RATED')], max_length=2)),
                ('year_of_production', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
