# Generated by Django 2.2.5 on 2019-11-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DownloadLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'SPECIFICATIONS'), ('V', 'VIDEO')], max_length=1)),
                ('link', models.URLField()),
                ('download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_watch_link', to='product.Product')),
            ],
        ),
    ]
