# Generated by Django 2.2.5 on 2019-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20191118_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('science', 'SCIENCE'), ('technology', 'TECHNOLOGY'), ('english', 'ENGINEERING'), ('mathematics', 'MATHEMATICS')], max_length=20),
        ),
    ]
