# Generated by Django 2.2.5 on 2019-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191118_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'ELECTRONICS'), ('medicalequipments', 'MEDICAL_EQUIPMENTS'), ('books', 'BOOKS'), ('movies', 'MOVIES')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('amharic', 'AMHARIC')], max_length=20),
        ),
    ]
